### ISSUE TITLE
go to line number or error

### ISSUE THREAD

**Issue by bkelly13** [arduino-libraries/Ethernet#113]
Please consider adding two options:
1.  Click on the error in the compile output and the IDE goes to that line.
2. User presses ctl-<something> 123 and the IDE goes to line 123

Thank you for your time.

**Comment by per1234** [comment]
This is the repository for the Arduino Ethernet library. Only bug reports or feature requests for the Ethernet library are on topic here. Since your issue report has nothing to do with the Ethernet library, I'll close it.

>Click on the error in the compile output and the IDE goes to that line.

We already have a feature request for this: https://github.com/arduino/Arduino/issues/3383
