### ISSUE TITLE
Overflow warning in htons()

### ISSUE THREAD

**Issue by habazut** [arduino-libraries/Ethernet#151]
In file included from /usr/share/arduino-1.8.13/libraries/Ethernet/src/Dns.cpp:8:0:
/usr/share/arduino-1.8.13/libraries/Ethernet/src/Dns.cpp: In member function 'uint16_t DNSClient::BuildRequest(const char*)':
/usr/share/arduino-1.8.13/libraries/Ethernet/src/utility/w5100.h:457:25: warning: result of '(256 << 8)' requires 18 bits to represent, but 'int' only has 16 bits [-Wshift-overflow=]
 #define htons(x) ( (((x)<<8)&0xFF00) | (((x)>>8)&0xFF) )

+++ Set a pragma to locally turn of that warning if you know about the overflow and it's OK. +++

Your library shall compile without warnings.

Regards,
Harald.

**Comment by jmnc2** [comment]
Is this lib not getting bug fixes any more?

**Comment by habazut** [comment]
Suggestion: 
#define htons(x) ( ((( x )&0xFF)<<8) | ((( x )&0xFF00)>>8) )

and for #pragma see google.

Regards,
Harald.

**Comment by GunZi200** [comment]
I am seeing this also: 

![image](https://user-images.githubusercontent.com/8218499/115287903-53bff500-a140-11eb-88ab-3bf10f44638f.png)

**Comment by GunZi200** [comment]
The real issue is line 164 in DNS.cpp

`twoByteBuffer = htons(QUERY_FLAG | OPCODE_STANDARD_QUERY | RECURSION_DESIRED_FLAG);`

change this to:

`twoByteBuffer = RECURSION_DESIRED_FLAG;`

Using `htons()` here makes little sense to me. Since `htons()` combines two bytes together while `RECURSION_DESIRED_FLAG` is part of a 16-bit mask.
