### ISSUE TITLE
Fix for potentially slow Client.stop() (no code changes)

### ISSUE THREAD

**Issue by lathoub** [arduino-libraries/Ethernet#215]
Calling the [stop()](https://github.com/arduino-libraries/Ethernet/blob/9e8a98cd745ee4b4e033819bcc38721fb15ab1b7/src/EthernetClient.cpp#L132-L152) function of the EthernetClient can be very slow. The timeout is set [by default to 1000ms](https://github.com/arduino-libraries/Ethernet/blob/64b394f9b5502f53c019d65b2ab998cdce7f8f2c/src/Ethernet.h#L216) (1s), in _timeout. 

https://github.com/arduino-libraries/Ethernet/blob/9e8a98cd745ee4b4e033819bcc38721fb15ab1b7/src/EthernetClient.cpp#L147

A simple fix to this is by calling `setConnectionTimeout` just before `stop().`
Example:

```cpp
client.setConnectionTimeout(5);
client.stop();
```

Reset the connection timeout prior to calling connect on the same client instance (if applicable)
FWIW

**Comment by per1234** [comment]
Thanks for sharing this tip @lathoub.

Since there is no action required in this codebase, and since the effect of the timeout on the `stop` method and its configurability [is already documented](https://www.arduino.cc/reference/en/libraries/ethernet/client.setconnectiontimeout/), I'll go ahead and close the issue. It will remain available in the repository's issues for the benefit of the library users.
