### ISSUE TITLE
Merge WIZnet fork

### ISSUE THREAD

**Issue by marek22k** [arduino-libraries/Ethernet#230]
WIZnet has made some new chips and it would be nice if someone could merge the PRs.

https://github.com/arduino-libraries/Ethernet/pull/185
https://github.com/arduino-libraries/Ethernet/pull/101
https://github.com/arduino-libraries/Ethernet/pull/102

Ping on maintainers: @per1234 @facchinm @aentinger @karlsoderby @cmaglie @PaulStoffregen

**Comment by per1234** [comment]
Hi @marek22k. Thanks for your interest in this open source project. The pull requests are sufficient for us to track the task of reviewing those proposals. Since this additional issue is superfluous, I'll go ahead and close it in the interest of keeping the repository tidy.

You are welcome to do careful and thorough testing and code review of those pull requests and then submit your findings via the GitHub pull request review system:

https://docs.github.com/pull-requests/collaborating-with-pull-requests/reviewing-changes-in-pull-requests/about-pull-request-reviews
